import Head from "next/head";
import { useEffect, useState } from "react";
import { drive_v3, auth } from "@googleapis/drive";
import { GoogleAuth } from "google-auth-library";
import styles from "../styles/Home.module.css";

// function authenticate() {
//   return auth
//       .OAuth2.({scope: "https://www.googleapis.com/auth/drive https://www.googleapis.com/auth/drive.appdata https://www.googleapis.com/auth/drive.file https://www.googleapis.com/auth/drive.metadata https://www.googleapis.com/auth/drive.metadata.readonly https://www.googleapis.com/auth/drive.photos.readonly https://www.googleapis.com/auth/drive.readonly"})
//       .then(function() { console.log("Sign-in successful"); },
//             function(err) { console.error("Error signing in", err); });
// }
// function loadClient() {
//   gapi.client.setApiKey("YOUR_API_KEY");
//   return gapi.client.load("https://content.googleapis.com/discovery/v1/apis/drive/v3/rest")
//       .then(function() { console.log("GAPI client loaded for API"); },
//             function(err) { console.error("Error loading GAPI client for API", err); });
// }

export default function Home() {
  const [result, setResult] = useState();

  // useEffect(() => {
  //   // const auth = new GoogleAuth({
  //   //   scopes: "https://www.googleapis.com/auth/drive",
  //   // });
  //   auth.OAuth2().then((r) => {

  //   })
  //   const service = new drive_v3.Drive({ auth });
  //   // Make sure the client is loaded and sign-in is complete before calling this method.
  //   function execute() {
  //     return service.files
  //       .list({
  //         orderBy: "createdTime",
  //         q: "name contains 'FitNotes_Backup.fitnotes' and trashed = false",
  //         fields: "files(id,name,createdTime)",
  //       })
  //       .then(
  //         function (response) {
  //           // Handle the results here (response.result has the parsed body).
  //           console.log("Response", response);
  //         },
  //         function (err) {
  //           console.error("Execute error", err);
  //         }
  //       );
  //   }
  //   execute();

  //   fetch("/api/hello")
  //     .then((r) => r.json())
  //     .then(setResult);
  // }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <pre>{JSON.stringify(result, null, 4)}</pre>
    </div>
  );
}
